USE [master]
GO

/****** Object:  Database [concesionaria]    Script Date: 10/8/2021 18:30:33 ******/
CREATE DATABASE [concesionaria]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'concesionaria', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\concesionaria.mdf' , SIZE = 8192KB , MAXSIZE = 10240KB , FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'concesionaria_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\concesionaria_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [concesionaria].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [concesionaria] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [concesionaria] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [concesionaria] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [concesionaria] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [concesionaria] SET ARITHABORT OFF 
GO

ALTER DATABASE [concesionaria] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [concesionaria] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [concesionaria] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [concesionaria] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [concesionaria] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [concesionaria] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [concesionaria] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [concesionaria] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [concesionaria] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [concesionaria] SET  DISABLE_BROKER 
GO

ALTER DATABASE [concesionaria] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [concesionaria] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [concesionaria] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [concesionaria] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [concesionaria] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [concesionaria] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [concesionaria] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [concesionaria] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [concesionaria] SET  MULTI_USER 
GO

ALTER DATABASE [concesionaria] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [concesionaria] SET DB_CHAINING OFF 
GO

ALTER DATABASE [concesionaria] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [concesionaria] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [concesionaria] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [concesionaria] SET QUERY_STORE = OFF
GO

ALTER DATABASE [concesionaria] SET  READ_WRITE 
GO


