USE [master]
GO

CREATE DATABASE [deposito_db]
 CONTAINMENT = NONE
 ON  PRIMARY 
 /*REEMPLAZAR LOS FILENAMES POR SU ESTRUCTURA DE DIRECTORIOS */
( NAME = N'deposito_db', FILENAME = N'C:\su ruta de direcorio\deposito_db.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 0)
 LOG ON 
 /*REEMPLAZAR LOS FILENAMES POR SU ESTRUCTURA DE DIRECTORIOS */
( NAME = N'deposito_db_log', FILENAME = N'C:\su ruta de directorio\deposito_db_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 0)
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [deposito_db].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [deposito_db] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [deposito_db] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [deposito_db] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [deposito_db] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [deposito_db] SET ARITHABORT OFF 
GO

ALTER DATABASE [deposito_db] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [deposito_db] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [deposito_db] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [deposito_db] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [deposito_db] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [deposito_db] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [deposito_db] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [deposito_db] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [deposito_db] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [deposito_db] SET  DISABLE_BROKER 
GO

ALTER DATABASE [deposito_db] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [deposito_db] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [deposito_db] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [deposito_db] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [deposito_db] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [deposito_db] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [deposito_db] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [deposito_db] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [deposito_db] SET  MULTI_USER 
GO

ALTER DATABASE [deposito_db] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [deposito_db] SET DB_CHAINING OFF 
GO

ALTER DATABASE [deposito_db] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [deposito_db] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [deposito_db] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [deposito_db] SET QUERY_STORE = OFF
GO

ALTER DATABASE [deposito_db] SET  READ_WRITE 
GO

USE [deposito_db]
GO


SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Articulos](
	[marca] [varchar](50) NOT NULL,
	[codigo] [int] NOT NULL,
	[precio] [float] NOT NULL
) ON [PRIMARY]
GO

