USE UTN_DB;

INSERT INTO MATERIAS (ID_MATERIA, DESCRIPCION, CUATRIMESTRE) 
VALUES (10, 'Programacion II', 2);

INSERT INTO MATERIAS (ID_MATERIA, DESCRIPCION, CUATRIMESTRE)
VALUES (7, 'Laboratorio II', 2);

INSERT INTO MATERIAS (ID_MATERIA, DESCRIPCION, CUATRIMESTRE)
VALUES (2, 'Matematica', 1);

INSERT INTO MATERIAS (ID_MATERIA, DESCRIPCION, CUATRIMESTRE)
VALUES (6, 'Arquitectura y Sist. Operativos', 2);


INSERT INTO ALUMNOS (NOMBRE, APELLIDO, PROMEDIO, ESTA_ACTIVO, FECHA_INSCRIPCION,
FECHA_GRADUACION, ID_MATERIA)
VALUES ('Esteban', 'Prieto', 9.7, 1, '2018-08-15', null, 2),
('Federico', 'Davila', 10, 1, '2014-05-15', '2016-12-10', null),
('Lucas', 'Rodriguez', 9.8, 0, '2018-08-15', null, 6),
('Carpincho', 'Profesor', 4, 0, '2000-03-01', null, null);

-- SELECT
SELECT NOMBRE, APELLIDO, FECHA_INSCRIPCION FROM ALUMNOS;

SELECT * FROM ALUMNOS;

SELECT * FROM ALUMNOS WHERE ID_ALUMNO = 103;

SELECT * FROM ALUMNOS WHERE ESTA_ACTIVO = 1;

SELECT * FROM ALUMNOS WHERE PROMEDIO > 4;

SELECT * FROM ALUMNOS WHERE FECHA_GRADUACION IS NOT NULL;

-- INNER JOIN. Los alumnos que cursan una materia y la materia que están cursando.
SELECT a.NOMBRE, a.APELLIDO, m.DESCRIPCION FROM ALUMNOS a
INNER JOIN MATERIAS m ON a.ID_MATERIA = m.ID_MATERIA;

-- LEFT JOIN. Todos los alumnos, curse o no y la materia que están cursando.
SELECT a.NOMBRE, a.APELLIDO, m.DESCRIPCION FROM ALUMNOS a
LEFT JOIN Materias m ON a.ID_MATERIA = M.ID_MATERIA;

-- RIGHT JOIN. Sólo los alumnas que cursan y todas las materias.
SELECT a.NOMBRE, a.APELLIDO, m.DESCRIPCION FROM ALUMNOS a
RIGHT JOIN Materias m ON a.ID_MATERIA = M.ID_MATERIA;