USE EMPRESA_DB;

INSERT INTO PUESTOS (ID_PUESTO, NOMBRE, NIVEL_AUTORIZACION)
VALUES (1, 'Director', 3),
(2, 'Gerente', 3),
(5, 'Jefe de sector', 2),
(4, 'Administrativo', 1),
(3, 'Vendedor', 0),
(6, 'Secretario', 2);

INSERT INTO EMPLEADOS (NOMBRE, APELLIDO, ID_PUESTO, SALARIO, ESTA_ACTIVO, FECHA_ALTA,
FECHA_BAJA, MAIL)
VALUES ('Leilani', 'Kinney', 1, 30000.80, 1, '1996-03-21', null, 'lkinney@gmail.com'),
('Igor', 'Scotland', 5, 26500.25, 1, '2013-03-28', null, '	iscotland@hotmail.com'),
('Maya', 'Brock', 3, 16800.65, 1, '1993-10-24', null, null),
('Hayden', 'Moss', 4, 211695.50, 0, '2012-06-07', '2015-02-19', 'hmoss@gmail.com'),
('Amal', 'Koln', 2, 388933.60, 1, '2019-09-23', null, null);

-- SELECT 1
-- i.
SELECT * FROM EMPLEADOS;

-- ii.
SELECT ID_PUESTO FROM EMPLEADOS; 

-- iii
SELECT * FROM EMPLEADOS WHERE ESTA_ACTIVO = 1;

-- iv 
SELECT * FROM EMPLEADOS WHERE SALARIO > 20000;

-- v
SELECT * FROM EMPLEADOS WHERE FECHA_ALTA <= '07-06-2012'

-- vi
SELECT * FROM EMPLEADOS WHERE MAIL IS NOT NULL;

-- vii
SELECT * FROM EMPLEADOS WHERE MAIL IS NULL;

-- vii
SELECT * FROM EMPLEADOS WHERE MAIL LIKE '%gmail%';

-- ix
SELECT * FROM EMPLEADOS WHERE APELLIDO LIKE 'B%';

-- SELECT 2
-- i
SELECT * FROM EMPLEADOS WHERE ESTA_ACTIVO IS NOT NULL AND SALARIO > 30000;

-- ii
SELECT * FROM EMPLEADOS WHERE ESTA_ACTIVO = 0 OR MAIL IS NULL;

-- iii
SELECT * FROM EMPLEADOS WHERE MAIL IS NOT NULL AND NOMBRE LIKE '%a%';

-- iv
SELECT * FROM EMPLEADOS WHERE SALARIO >= 25000 AND FECHA_ALTA > '2000-01-01';

-- v
SELECT * FROM EMPLEADOS WHERE SALARIO BETWEEN 20000 AND 35000;

-- vi 
SELECT * FROM EMPLEADOS WHERE SALARIO NOT BETWEEN 20000 AND 35000;

-- vii
SELECT * FROM EMPLEADOS WHERE ID_PUESTO IN (3, 4, 5 ,6);

-- viii
SELECT * FROM EMPLEADOS WHERE ID_PUESTO NOT IN (3, 4, 5 ,6);

-- SELECT 3
-- i
SELECT NOMBRE, APELLIDO FROM EMPLEADOS WHERE ESTA_ACTIVO = 1 ORDER BY APELLIDO ASC;

-- ii
SELECT TOP(3) NOMBRE, APELLIDO, FECHA_ALTA FROM EMPLEADOS ORDER BY FECHA_ALTA ASC; 

-- iii
SELECT TOP(3) NOMBRE, APELLIDO, SALARIO FROM EMPLEADOS ORDER BY SALARIO DESC;

-- iv
SELECT NOMBRE, APELLIDO, SALARIO FROM EMPLEADOS ORDER BY SALARIO DESC;

-- v
SELECT DISTINCT NIVEL_AUTORIZACION FROM PUESTOS;

-- SELECT 4
-- i
SELECT e.NOMBRE, e.APELLIDO, p.NOMBRE FROM EMPLEADOS e
INNER JOIN PUESTOS p ON e.ID_PUESTO = p.ID_PUESTO;

-- ii
SELECT e.NOMBRE, e.APELLIDO, p.NOMBRE, p.NIVEL_AUTORIZACION FROM EMPLEADOS e
INNER JOIN PUESTOS p ON e.ID_PUESTO = p.ID_PUESTO
WHERE p.NIVEL_AUTORIZACION = 3;

-- iii 
SELECT e.NOMBRE, e.APELLIDO, p.NOMBRE FROM EMPLEADOS e
INNER JOIN PUESTOS p ON e.ID_PUESTO = p.ID_PUESTO
ORDER BY e.NOMBRE;

-- iv
SELECT e.NOMBRE, e.APELLIDO, p.NOMBRE FROM EMPLEADOS e
INNER JOIN PUESTOS p ON e.ID_PUESTO = p.ID_PUESTO
ORDER BY p.NOMBRE;

-- v 
SELECT e.NOMBRE, e.APELLIDO, p.NOMBRE, p.NIVEL_AUTORIZACION FROM EMPLEADOS e
INNER JOIN PUESTOS p ON e.ID_PUESTO = p.ID_PUESTO
WHERE e.ESTA_ACTIVO = 1
ORDER BY p.NIVEL_AUTORIZACION;

-- vi 
SELECT p.* FROM PUESTOS p
LEFT JOIN EMPLEADOS e ON e.ID_PUESTO = p.ID_PUESTO
WHERE e.ID_EMPLEADO IS NULL;

-- vii
SELECT DISTINCT p.* FROM PUESTOS p
INNER JOIN EMPLEADOS e ON e.ID_PUESTO = p.ID_PUESTO;

-- Punto 10
SELECT * FROM EMPLEADOS;
UPDATE EMPLEADOS SET MAIL = 'mbrock@yahoo.com' WHERE ID_EMPLEADO = 3;

-- Punto 11
UPDATE EMPLEADOS SET ID_PUESTO = 4, SALARIO = 210000 WHERE ID_EMPLEADO = 3;

-- Punto 12
UPDATE EMPLEADOS SET SALARIO = SALARIO + (SALARIO * 0.25) WHERE SALARIO <= 200000;

-- Punto 13 
-- Exportar 

-- Punto 14
UPDATE EMPLEADOS SET ESTA_ACTIVO = 0, FECHA_BAJA = GETDATE() WHERE ID_EMPLEADO = 1;

-- Punto 15
DELETE FROM EMPLEADOS WHERE ESTA_ACTIVO = 0;  